name: CI/CD Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Copy to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ubuntu
        key: ${{ secrets.EC2_ACCESS_KEY }}
        debug: true
        source: "index.html"
        target: /var/www/CloudComputing-Ecommerce

    - name: Run app with PM2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOSTNAME }}
        username: ubuntu
        key: ${{ secrets.EC2_ACCESS_KEY }}
        script: |
          sudo cd /var/www/CloudComputing-Ecommerce
          sudo systemctl restart nginx
