name: CI/CD Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_ACCESS_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOSTNAME }} >> ~/.ssh/known_hosts

    - name: Copy to EC2
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ./* ec2-user@${{ secrets.EC2_HOSTNAME }}:/var/www/CloudComputing-Ecommerce

    - name: Run app with PM2
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOSTNAME }} << 'EOF'
          cd /var/www/CloudComputing-Ecommerce
          sudo systemctl restart nginx
        EOF
